services:
  db:
    image: postgres:15
    container_name: clinica_medica_db
    environment:
      POSTGRES_DB: clinica_medica
      POSTGRES_USER: clinica_user
      POSTGRES_PASSWORD: clinica_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinica_user -d clinica_medica"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: clinica_medica_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://clinica_user:clinica_password@db:5432/clinica_medica
      - SECRET_KEY=sua-chave-secreta-muito-segura-para-producao-clinica-medica-2024
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  test-db:
    image: postgres:15
    container_name: clinica_medica_test_db
    environment:
      POSTGRES_DB: clinica_medica_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d clinica_medica_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  tests:
    build: .
    container_name: clinica_medica_tests
    environment:
      - DATABASE_URL=postgresql://test_user:test_password@test-db:5432/clinica_medica_test
      - SECRET_KEY=chave-secreta-para-testes-clinica-medica-2024
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    depends_on:
      test-db:
        condition: service_healthy
    command: ["python", "-m", "pytest", "tests/", "-v"]
    profiles:
      - test

volumes:
  postgres_data:
  test_postgres_data: