version: "3.7"

services:
  db:
    image: postgres:15
    container_name: postgres-db-ttpe
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ttpeclinic
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

  test:
    build: .
    container_name: test
    command: pytest main/tests/.
